from PySide6.QtCore import (QCoreApplication, QMetaObject, QRect, QSize, Qt)
from PySide6.QtGui import QFont
from PySide6.QtWidgets import (QLineEdit, QPushButton)

class Ui_Calc(object):
    def setupUi(self, Calc):
        if not Calc.objectName():
            Calc.setObjectName(u"Calc")
        Calc.resize(430, 350)
        Calc.setMinimumSize(QSize(430, 350))
        Calc.setMaximumSize(QSize(430, 350))
        Calc.setStyleSheet(u"background-color: rgb(194, 194, 194);")
        self.Button0 = QPushButton(Calc)
        self.Button0.setObjectName(u"Button0")
        self.Button0.setGeometry(QRect(120, 270, 90, 51))
        font = QFont()
        font.setPointSize(12)
        self.Button0.setFont(font)
        self.Button0.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.ButtonResult = QPushButton(Calc)
        self.ButtonResult.setObjectName(u"ButtonResult")
        self.ButtonResult.setGeometry(QRect(20, 270, 91, 51))
        self.ButtonResult.setFont(font)
        self.ButtonResult.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.Button1 = QPushButton(Calc)
        self.Button1.setObjectName(u"Button1")
        self.Button1.setGeometry(QRect(20, 90, 90, 51))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(12)
        self.Button1.setFont(font1)
        self.Button1.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.Button2 = QPushButton(Calc)
        self.Button2.setObjectName(u"Button2")
        self.Button2.setGeometry(QRect(120, 90, 90, 51))
        self.Button2.setFont(font)
        self.Button2.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.Button3 = QPushButton(Calc)
        self.Button3.setObjectName(u"Button3")
        self.Button3.setGeometry(QRect(220, 90, 90, 51))
        self.Button3.setFont(font)
        self.Button3.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.Button4 = QPushButton(Calc)
        self.Button4.setObjectName(u"Button4")
        self.Button4.setGeometry(QRect(20, 150, 90, 51))
        self.Button4.setFont(font)
        self.Button4.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.Button5 = QPushButton(Calc)
        self.Button5.setObjectName(u"Button5")
        self.Button5.setGeometry(QRect(120, 150, 90, 51))
        self.Button5.setFont(font)
        self.Button5.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.Button6 = QPushButton(Calc)
        self.Button6.setObjectName(u"Button6")
        self.Button6.setGeometry(QRect(220, 150, 90, 51))
        self.Button6.setFont(font)
        self.Button6.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.Button7 = QPushButton(Calc)
        self.Button7.setObjectName(u"Button7")
        self.Button7.setGeometry(QRect(20, 210, 90, 51))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(False)
        self.Button7.setFont(font2)
        self.Button7.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.Button8 = QPushButton(Calc)
        self.Button8.setObjectName(u"Button8")
        self.Button8.setGeometry(QRect(120, 210, 90, 51))
        self.Button8.setFont(font)
        self.Button8.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.Button9 = QPushButton(Calc)
        self.Button9.setObjectName(u"Button9")
        self.Button9.setGeometry(QRect(220, 210, 90, 51))
        self.Button9.setFont(font)
        self.Button9.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.ButtonAdd = QPushButton(Calc)
        self.ButtonAdd.setObjectName(u"ButtonAdd")
        self.ButtonAdd.setGeometry(QRect(320, 90, 90, 51))
        self.ButtonAdd.setFont(font)
        self.ButtonAdd.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.ButtonSub = QPushButton(Calc)
        self.ButtonSub.setObjectName(u"ButtonSub")
        self.ButtonSub.setGeometry(QRect(320, 150, 90, 51))
        self.ButtonSub.setFont(font)
        self.ButtonSub.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.ButtonMult = QPushButton(Calc)
        self.ButtonMult.setObjectName(u"ButtonMult")
        self.ButtonMult.setGeometry(QRect(320, 210, 90, 51))
        self.ButtonMult.setFont(font)
        self.ButtonMult.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.ButtonDiv = QPushButton(Calc)
        self.ButtonDiv.setObjectName(u"ButtonDiv")
        self.ButtonDiv.setGeometry(QRect(320, 270, 90, 51))
        self.ButtonDiv.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.LineResult = QLineEdit(Calc)
        self.LineResult.setObjectName(u"LineResult")
        self.LineResult.setGeometry(QRect(20, 25, 390, 51))
        self.LineResult.setFont(font)
        self.LineResult.setStyleSheet(u"background-color:rgb(231, 231, 231)")
        self.LineResult.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.ButtonC = QPushButton(Calc)
        self.ButtonC.setObjectName(u"ButtonC")
        self.ButtonC.setGeometry(QRect(220, 270, 90, 51))
        self.ButtonC.setFont(font)
        self.ButtonC.setStyleSheet(u"background-color:rgb(231, 231, 231)")

        self.retranslateUi(Calc)

        QMetaObject.connectSlotsByName(Calc)
    # setupUi

    def add_functions(self):
        self.Button0.clicked.connect(lambda: self.write_number(self.Button0.text()))
        self.Button1.clicked.connect(lambda: self.write_number(self.Button1.text()))
        self.Button2.clicked.connect(lambda: self.write_number(self.Button2.text()))
        self.Button3.clicked.connect(lambda: self.write_number(self.Button3.text()))
        self.Button4.clicked.connect(lambda: self.write_number(self.Button4.text()))
        self.Button5.clicked.connect(lambda: self.write_number(self.Button5.text()))
        self.Button6.clicked.connect(lambda: self.write_number(self.Button6.text()))
        self.Button7.clicked.connect(lambda: self.write_number(self.Button7.text()))
        self.Button8.clicked.connect(lambda: self.write_number(self.Button8.text()))
        self.Button9.clicked.connect(lambda: self.write_number(self.Button9.text()))
        self.ButtonAdd.clicked.connect(lambda: self.write_number(self.ButtonAdd.text()))
        self.ButtonSub.clicked.connect(lambda: self.write_number(self.ButtonSub.text()))
        self.ButtonMult.clicked.connect(lambda: self.write_number(self.ButtonMult.text()))
        self.ButtonDiv.clicked.connect(lambda: self.write_number(self.ButtonDiv.text()))
        self.ButtonResult.clicked.connect(self.result)
        self.ButtonC.clicked.connect(self.clear)

    def write_number(self, number):
        if self.LineResult.text() == "0":
            self.LineResult.setText(number)
        else:
                self.LineResult.setText(self.LineResult.text() + number)

    def result(self):
        try:
            res = eval(self.LineResult.text())
            self.LineResult.setText(str(res))
        except:
            self.LineResult.setText("Invalid Syntax")

    def clear(self):
        self.LineResult.clear()

    def retranslateUi(self, Calc):
        Calc.setWindowTitle(QCoreApplication.translate("Calc", u"Calc", None))
        self.Button0.setText(QCoreApplication.translate("Calc", u"0", None))
        self.ButtonResult.setText(QCoreApplication.translate("Calc", u"=", None))
        self.Button1.setText(QCoreApplication.translate("Calc", u"1", None))
        self.Button2.setText(QCoreApplication.translate("Calc", u"2", None))
        self.Button3.setText(QCoreApplication.translate("Calc", u"3", None))
        self.Button4.setText(QCoreApplication.translate("Calc", u"4", None))
        self.Button5.setText(QCoreApplication.translate("Calc", u"5", None))
        self.Button6.setText(QCoreApplication.translate("Calc", u"6", None))
        self.Button7.setText(QCoreApplication.translate("Calc", u"7", None))
        self.Button8.setText(QCoreApplication.translate("Calc", u"8", None))
        self.Button9.setText(QCoreApplication.translate("Calc", u"9", None))
        self.ButtonAdd.setText(QCoreApplication.translate("Calc", u"+", None))
        self.ButtonSub.setText(QCoreApplication.translate("Calc", u"-", None))
        self.ButtonMult.setText(QCoreApplication.translate("Calc", u"*", None))
        self.ButtonDiv.setText(QCoreApplication.translate("Calc", u"/", None))
        self.ButtonC.setText(QCoreApplication.translate("Calc", u"C", None))
    # retranslateUi

